name: nn4cast-env
channels:
  - defaults
dependencies:
  - numpy==1.23.5
  - matplotlib==3.7.1
  - pandas==1.5.3
  - xarray==2023.2.0
  - scipy==1.10.1
  - cartopy==0.21.1
  - xskillscore==0.0.24
  - tensorflow==2.10.0
  - keras==2.10.0
  - kerastuner==1.3.4
  - scikit-learn==1.2.1
